In [1]:
# Import important library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

### Read the input file and check the data dimension

In [2]:
credit_data=pd.read_csv('german_credit.csv')
credit_data.head(5)

,default,account_check_status,duration_in_month,credit_history,purpose,credit_amount,savings,present_emp_since,installment_as_income_perc,personal_status_sex,...,present_res_since,property,age,other_installment_plans,housing,credits_this_bank,job,people_under_maintenance,telephone,foreign_worker
0,0,< 0 DM,6,critical account/ other credits existing (not ...,domestic appliances,1169,unknown/ no savings account,.. >= 7 years,4,male : single,...,4,real estate,67,none,own,2,skilled employee / official,1,"yes, registered under the customers name",yes
1,1,0 <= ... < 200 DM,48,existing credits paid back duly till now,domestic appliances,5951,... < 100 DM,1 <= ... < 4 years,2,female : divorced/separated/married,...,2,real estate,22,none,own,1,skilled employee / official,1,none,yes
2,0,no checking account,12,critical account/ other credits existing (not ...,(vacation - does not exist?),2096,... < 100 DM,4 <= ... < 7 years,2,male : single,...,3,real estate,49,none,own,1,unskilled - resident,2,none,yes
3,0,< 0 DM,42,existing credits paid back duly till now,radio/television,7882,... < 100 DM,4 <= ... < 7 years,2,male : single,...,4,if not A121 : building society savings agreeme...,45,none,for free,1,skilled employee / official,2,none,yes
4,1,< 0 DM,24,delay in paying off in the past,car (new),4870,... < 100 DM,1 <= ... < 4 years,3,male : single,...,4,unknown / no property,53,none,for free,2,skilled employee / official,2,none,yes

In [3]:
# You can access from https://www.kaggle.com/uciml/german-credit
#Read input file and understand the data
# "default" is my dependent variable

### Q1 Randomly select 50% data for this use case( 1 Marks)
###### Hint: Use train_test_split

In [4]:
#Why to use train_test_split if we can use sample to get random 50% data
random_new_data = credit_data.sample(frac=0.5)

In [5]:
# Lets build a Ensemble model but need to modify the dataset first
random_new_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 500 entries, 182 to 717
Data columns (total 21 columns):
default                       500 non-null int64
account_check_status          500 non-null object
duration_in_month             500 non-null int64
credit_history                500 non-null object
purpose                       500 non-null object
credit_amount                 500 non-null int64
savings                       500 non-null object
present_emp_since             500 non-null object
installment_as_income_perc    500 non-null int64
personal_status_sex           500 non-null object
other_debtors                 500 non-null object
present_res_since             500 non-null int64
property                      500 non-null object
age                           500 non-null int64
other_installment_plans       500 non-null object
housing                       500 non-null object
credits_this_bank             500 non-null int64
job                           500 non-null object
people_under_maintenance      500 non-null int64
telephone                     500 non-null object
foreign_worker                500 non-null object
dtypes: int64(8), object(13)
memory usage: 85.9+ KB

### Q2.Prepare the model data by converting non-numeric to dummy ( 1 Marks)
##### Hint: Use get_dummies

In [6]:
# Print Shape of model data
#I am rather using label encoder than to use dummy columns since there are huge number of categorical values

In [7]:
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing
list_to_labelencoding = ['account_check_status','credit_history','purpose','savings','present_emp_since',
                        'personal_status_sex','other_debtors','property','other_installment_plans','housing',
                        'job','telephone','foreign_worker']
for colname in list_to_labelencoding:
    le = preprocessing.LabelEncoder()
    random_new_data[colname] = le.fit_transform(random_new_data[colname])

random_new_data.head()

,default,account_check_status,duration_in_month,credit_history,purpose,credit_amount,savings,present_emp_since,installment_as_income_perc,personal_status_sex,...,present_res_since,property,age,other_installment_plans,housing,credits_this_bank,job,people_under_maintenance,telephone,foreign_worker
182,1,1,21,0,2,1647,4,2,4,3,...,2,0,40,1,1,2,3,2,0,1
744,0,1,39,1,7,14179,4,3,4,3,...,4,0,30,1,1,2,0,1,1,1
414,1,1,24,3,2,1381,4,2,4,0,...,2,0,35,1,1,1,1,1,0,1
946,1,1,24,0,7,3349,3,1,4,3,...,4,3,30,1,0,1,1,2,1,1
931,1,0,9,3,4,1670,1,1,4,0,...,2,1,22,1,1,1,1,1,1,1

In [8]:
random_new_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 500 entries, 182 to 717
Data columns (total 21 columns):
default                       500 non-null int64
account_check_status          500 non-null int32
duration_in_month             500 non-null int64
credit_history                500 non-null int32
purpose                       500 non-null int32
credit_amount                 500 non-null int64
savings                       500 non-null int32
present_emp_since             500 non-null int32
installment_as_income_perc    500 non-null int64
personal_status_sex           500 non-null int32
other_debtors                 500 non-null int32
present_res_since             500 non-null int64
property                      500 non-null int32
age                           500 non-null int64
other_installment_plans       500 non-null int32
housing                       500 non-null int32
credits_this_bank             500 non-null int64
job                           500 non-null int32
people_under_maintenance      500 non-null int64
telephone                     500 non-null int32
foreign_worker                500 non-null int32
dtypes: int32(13), int64(8)
memory usage: 60.5 KB

### Check for highly correlated variables but don't required any treatment for this use case

In [9]:
random_new_data.corr()

,default,account_check_status,duration_in_month,credit_history,purpose,credit_amount,savings,present_emp_since,installment_as_income_perc,personal_status_sex,...,present_res_since,property,age,other_installment_plans,housing,credits_this_bank,job,people_under_maintenance,telephone,foreign_worker
default,1.000000,-0.314052,0.181166,0.087515,-0.058624,0.107861,-0.117692,0.013277,0.021462,-0.039704,...,0.013312,0.040740,-0.026650,-0.049484,-0.029816,-0.015964,-0.009616,0.030508,-0.072890,0.072728
account_check_status,-0.314052,1.000000,-0.112631,-0.097525,0.036153,-0.136143,0.142246,-0.097795,0.071738,0.016980,...,0.022552,-0.037423,0.088176,-0.016631,-0.008094,0.104076,-0.047495,0.022846,0.037209,0.023156
duration_in_month,0.181166,-0.112631,1.000000,0.025219,-0.084185,0.635171,0.080851,0.012913,0.076270,0.129576,...,0.052445,0.106885,0.002351,0.045361,-0.187958,-0.009982,-0.204690,0.020524,0.122104,0.092921
credit_history,0.087515,-0.097525,0.025219,1.000000,0.107926,0.026211,0.005801,0.005828,-0.082012,-0.069257,...,-0.096443,-0.034494,-0.128508,-0.015885,0.034064,-0.389271,-0.028177,-0.050751,-0.025281,-0.010245
purpose,-0.058624,0.036153,-0.084185,0.107926,1.000000,-0.079403,-0.040527,0.019621,-0.033157,-0.047874,...,-0.068177,-0.114208,-0.133659,0.023736,0.080042,-0.096316,0.002802,-0.075231,-0.054202,-0.027406
credit_amount,0.107861,-0.136143,0.635171,0.026211,-0.079403,1.000000,0.108168,0.090940,-0.254542,0.184317,...,0.039090,0.063709,0.046148,0.016166,-0.093989,0.029514,-0.283626,0.058789,0.265953,-0.002051
savings,-0.117692,0.142246,0.080851,0.005801,-0.040527,0.108168,1.000000,-0.015591,-0.033162,0.064560,...,0.081076,-0.114735,0.013386,-0.019526,-0.022253,-0.078834,-0.047933,0.021924,0.078698,-0.003217
present_emp_since,0.013277,-0.097795,0.012913,0.005828,0.019621,0.090940,-0.015591,1.000000,-0.151662,-0.036812,...,-0.190210,-0.051906,-0.271965,0.095660,0.037777,-0.043813,-0.056684,-0.091549,0.001078,-0.054773
installment_as_income_perc,0.021462,0.071738,0.076270,-0.082012,-0.033157,-0.254542,-0.033162,-0.151662,1.000000,0.106121,...,0.033141,0.061683,0.104294,0.033526,-0.130625,0.070116,-0.047972,-0.067152,0.032613,0.053396
personal_status_sex,-0.039704,0.016980,0.129576,-0.069257,-0.047874,0.184317,0.064560,-0.036812,0.106121,1.000000,...,0.034336,0.094338,0.165953,0.064601,-0.271498,0.069157,-0.070069,0.266890,0.116598,-0.028768
other_debtors,-0.002789,0.037034,0.029772,0.029474,-0.075142,0.012403,0.048270,-0.041120,-0.009005,-0.016479,...,0.012843,-0.077420,0.051352,0.036363,-0.032866,0.025697,-0.048386,0.056083,0.077856,0.165134
present_res_since,0.013312,0.022552,0.052445,-0.096443,-0.068177,0.039090,0.081076,-0.190210,0.033141,0.034336,...,1.000000,0.116996,0.288891,-0.008337,-0.039288,0.131796,0.005910,0.105033,0.136005,0.091738
property,0.040740,-0.037423,0.106885,-0.034494,-0.114208,0.063709,-0.114735,-0.051906,0.061683,0.094338,...,0.116996,1.000000,0.128400,-0.037774,-0.364024,-0.005730,-0.035757,0.086565,-0.004724,0.069384
age,-0.026650,0.088176,0.002351,-0.128508,-0.133659,0.046148,0.013386,-0.271965,0.104294,0.165953,...,0.288891,0.128400,1.000000,-0.034633,-0.262057,0.138749,-0.046078,0.150341,0.190248,0.024051
other_installment_plans,-0.049484,-0.016631,0.045361,-0.015885,0.023736,0.016166,-0.019526,0.095660,0.033526,0.064601,...,-0.008337,-0.037774,-0.034633,1.000000,0.011559,0.015743,0.004363,-0.082118,0.011262,0.048621
housing,-0.029816,-0.008094,-0.187958,0.034064,0.080042,-0.093989,-0.022253,0.037777,-0.130625,-0.271498,...,-0.039288,-0.364024,-0.262057,0.011559,1.000000,0.014756,0.145187,-0.177170,-0.121053,-0.066088
credits_this_bank,-0.015964,0.104076,-0.009982,-0.389271,-0.096316,0.029514,-0.078834,-0.043813,0.070116,0.069157,...,0.131796,-0.005730,0.138749,0.015743,0.014756,1.000000,-0.002423,0.143204,0.064804,-0.005593
job,-0.009616,-0.047495,-0.204690,-0.028177,0.002802,-0.283626,-0.047933,-0.056684,-0.047972,-0.070069,...,0.005910,-0.035757,-0.046078,0.004363,0.145187,-0.002423,1.000000,0.094997,-0.390956,-0.083805
people_under_maintenance,0.030508,0.022846,0.020524,-0.050751,-0.075231,0.058789,0.021924,-0.091549,-0.067152,0.266890,...,0.105033,0.086565,0.150341,-0.082118,-0.177170,0.143204,0.094997,1.000000,-0.004089,0.021781
telephone,-0.072890,0.037209,0.122104,-0.025281,-0.054202,0.265953,0.078698,0.001078,0.032613,0.116598,...,0.136005,-0.004724,0.190248,0.011262,-0.121053,0.064804,-0.390956,-0.004089,1.000000,0.088376
foreign_worker,0.072728,0.023156,0.092921,-0.010245,-0.027406,-0.002051,-0.003217,-0.054773,0.053396,-0.028768,...,0.091738,0.069384,0.024051,0.048621,-0.066088,-0.005593,-0.083805,0.021781,0.088376,1.000000

### Drop the original variables which are converted to dummy

In [10]:
#no dummies created

### Q3 Split Train/Test data 70:30 ratio( 1 Marks)
##### Hint:from sklearn.model_selection import train_test_split

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X=random_new_data.drop(labels=['default'],axis='columns')
y=random_new_data['default']
test_size=0.30
seed =1 # Random numbmer seeding for reapeatability of the code
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=seed)

### Q4 Build Random Forest Model( 1 Marks)
#### Hint:from sklearn.ensemble import RandomForestClassifier using n_jobs=2,n_estimators=500,criterion="entropy",random_state=9999

In [13]:
from sklearn.ensemble import RandomForestClassifier

In [14]:
rfcl = RandomForestClassifier(n_estimators=500,criterion="entropy",random_state=9999,n_jobs=2)
rfcl = rfcl.fit(X_train,y_train)

In [15]:
test_pred = rfcl.predict(X_test)
rfcl.score(X_test,y_test)

0.76

### Q5 Calculate Confusion Matrix and Accuracy score (1 Marks)
##### Hint: Use confusion_matrix and accuracy_score

In [16]:
from sklearn import metrics

In [17]:
print(metrics.classification_report(y_test, test_pred))
print(metrics.confusion_matrix(y_test, test_pred))

              precision    recall  f1-score   support

           0       0.80      0.90      0.85       110
           1       0.58      0.38      0.45        40

   micro avg       0.76      0.76      0.76       150
   macro avg       0.69      0.64      0.65       150
weighted avg       0.74      0.76      0.74       150

[[99 11]
 [25 15]]

### Q6 Show the list of the features importance( 1 Marks)

In [18]:
#import seaborn as sns
#sns.pairplot(random_new_data, diag_kind='kde',hue='default')

### Q7 K-fold cross-validation( 2 Marks)
##### k-fold cross validation( without stratification)
##### Usually k is set as 10-20 in practical settings, depends on data set size

In [20]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score,cross_val_predict
scores = cross_val_score(rfcl, X, y, cv=10)

In [ ]:
predictions = cross_val_predict(rfcl, X, y, cv=10)
accuracy = metrics.r2_score(y, predictions)
print(accuracy)

In [ ]:
# Use below values
num_folds = 10
seed = 77

In [ ]:
#Validate the Random Forest model build above using k fold

In [ ]:
kf = KFold(n_splits=2) # Define the split - into 2 folds 
kf.get_n_splits(X)
print(kf)

In [ ]:
KFold(n_splits=2, random_state=None, shuffle=False)

In [ ]:
for train_index, test_index in kf.split(X):
    X_train_k, X_test_k = X[train_index], X[test_index]
    y_train_k, y_test_k = y[train_index], y[test_index]

In [ ]:
#Calculate Mean score

In [ ]:
# Calculate score standard deviation using std()

# Q8 Print the confusion matrix( 1 Marks)

# Q9.Classification accuracy: 
percentage of correct predictions and Calculate sensitivity (or True Positive Rate or Recall) and Precision.
( 1 Marks)

# Q10.Plot Receiver Operating Characteristic (ROC) Curves( 1 Marks)

In [ ]:
#Hint: Use roc_curve

ROC curve can help you to choose a threshold that balances sensitivity and specificity in a way that makes sense for your particular context

# Q11. Calculate AUC(the percentage of the ROC plot that is underneath the curve) - optional

### Bootstrapping ( Bonus)
##### Given a dataset of size n, a bootstrap sample is created by sampling n instances uniformly from the data (with/without replacement)
##### Create a model with each bootstrap sample and validate it with the test set
##### Final result is calculated by averaging the accuracy of models

In [ ]:
# Number of iterations for bootstrapping
bootstrap_iteration = 10
accuracy = []

In [ ]:
from sklearn.utils import resample
from sklearn.metrics import accuracy_score

for i in range(bootstrap_iteration):
    X_, y_ = resample(X_train, y_train)
    rfm.fit(X_, y_)
    y_pred = rfm.predict(X_test)
    
    acc = accuracy_score(y_pred, y_test)
    accuracy.append(acc)

In [ ]:
accuracy = np.array(accuracy)
print('Accuracy Score')
print('Avearge: ', accuracy.mean())
print('Standard deviation: ', accuracy.std())